name: Docs
on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    name: sphinx build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.8
        julia-version:
          - 1.6.2
    steps:
      - uses: actions/checkout@v2
      - name: setup julia
        uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: install deps
        run: |
          pip install -r dev-requirements.txt
      - name: sphinx
        run: |
          cd docs
          make clean dirhtml
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/dirhtml/
          force_orphan: true